# Generated by Django 5.1.4 on 2025-01-09 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0003_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='CartItem',
        ),
    ]
